baseURL = 'https://pin-yu.github.io'
languageCode = 'en-us'
title = "Pin-Yu's Blog"
theme = 'hugo-theme-cleanwhite'

[params]
  header_image = "img/home-bg.jpg"
  SEOTitle = "Pin-Yu's Blog"
  description = "Pin-Yu's Blog"
  keyword = ""
  slogan = "持續學習"

  title_404 = "400 + 4 = 404"
  omit_categories = false
